version: "2.4"

services:
  mysql:
    image: mysql:5.7
    networks: [ "backend" ]
    ports:
    - ${PHP_DEMO_MYSQL_PORT:-3306}:3306
    volumes:
    - mysql_data:/var/lib/mysql
    - ./database/dumps:/database/dumps
    - ./database/create_databases.sql:/docker-entrypoint-initdb.d/001_create_databases.sql
    environment:
      MYSQL_USER: demo
      MYSQL_PASSWORD: 3x4mpl3P455w0rd
      MYSQL_ROOT_PASSWORD: 3x4mpl3P455w0rd

  redis:
    image: redis:3-alpine
    ports:
    - ${PHP_DEMO_REDIS_PORT:-6379}:6379
    volumes:
    - redis_data:/var/lib/redis
    command: redis-server --appendonly yes
    networks: [ "backend" ]
